### ISSUE TITLE
Roadmap migration (1.7.5)

### ISSUE THREAD

**Issue by mickaelandrieu** [PrestaShop/prestafony-project#10]
- Sell
  - Orders
    - [x] [Invoices](https://github.com/PrestaShop/PrestaShop/pull/9230)
    - [x] [Delivery Slips](https://github.com/PrestaShop/PrestaShop/pull/9139)
  - Catalog
    - [x] Categories ([WIP only Grid view](https://github.com/PrestaShop/PrestaShop/pull/10160) by @sarjon )
    - [ ] Categories (new/edit action form) (Stuck by https://github.com/PrestaShop/prestafony-project/issues/56)
- Improve
  - Design
     - [x] [Theme Catalog](https://github.com/PrestaShop/PrestaShop/pull/9154)
     - [x] [Positions](https://github.com/PrestaShop/PrestaShop/pull/9228)
     - [ ] [Link Widget](https://github.com/PrestaShop/prestafony-project/issues/25) (WIP - Joe)
  - Shipping
    - [x] [Preferences](https://github.com/PrestaShop/PrestaShop/pull/9094)
  - Payment
    - [x] [Payment methods](https://github.com/PrestaShop/PrestaShop/pull/9192) (modules configuration pages excluded)
    - [x] [Preferences](https://github.com/PrestaShop/PrestaShop/pull/9225)
  - International
    - [x] [Localization](https://github.com/PrestaShop/PrestaShop/pull/9116)
    - [x] [Geolocation](https://github.com/PrestaShop/PrestaShop/pull/9176)
    - [ ] Currencies (Grid view)
    - [ ] Currencies (new/edit form action) (Stuck by https://github.com/PrestaShop/prestafony-project/issues/56)
    - [x] [Translations](https://github.com/PrestaShop/PrestaShop/pull/9449)
- Configure
  - Shop Parameters
    - [x] [Order Settings](https://github.com/PrestaShop/PrestaShop/pull/9007)
    - [ ] SEO & URL (Grid view) + https://github.com/PrestaShop/PrestaShop/issues/10123
    - [ ] SEO & URL (new/edit form action) (Stuck by https://github.com/PrestaShop/prestafony-project/issues/56)
  - Advanced Parameters 
    - [X] [LogsPage](https://github.com/PrestaShop/PrestaShop/pull/9457)
    - [X] [Emails](https://github.com/PrestaShop/PrestaShop/pull/9377)  
    - Database
      - [x] [SQL Manager](https://github.com/PrestaShop/PrestaShop/pull/9206)
      - [x] [DB Backup](https://github.com/PrestaShop/PrestaShop/pull/9447)
    - Webservice
      - [X] [List keys + config](https://github.com/PrestaShop/PrestaShop/pull/10208)
      - [ ] [Add new key](https://github.com/PrestaShop/prestafony-project/issues/37) (Stuck by https://github.com/PrestaShop/prestafony-project/issues/56)

- [x] [Security annotations](https://github.com/PrestaShop/PrestaShop/pull/9028)
- [x] [Grid component](https://github.com/PrestaShop/PrestaShop/pull/8990), including [Search](https://github.com/PrestaShop/PrestaShop/pull/8984)
- [x] [Find a way to migrate Module Controllers](https://github.com/PrestaShop/PrestaShop/pull/9153)
- [ ] More tests and docs!
   - [ ] [Make a learning module about the Grid system](https://github.com/PrestaShop/prestafony-project/issues/63)
   - [x] [Document Grid system](https://devdocs.prestashop.com/1.7/development/components/grid-component/)
   - [x] [Document How to contribute to the Core](https://devdocs.prestashop.com/1.7/contribute/)
   - [ ] Document How to configure sessions for horizontal scaling
   - [ ] Document How to create tests in Modules
   - [ ] Document How to use Composer in Modules
   - [X] [Document How to override Back Office templates](https://devdocs.prestashop.com/1.7/modules/concepts/templating/admin-views/)
   - [ ] Document How to use and override Ps 1.7 services in modules
   - [x] [Document How to use and override Ps 1.7 commands in modules](https://github.com/PrestaShop/docs/pull/124)
   - [X] [Document How to use and override Ps 1.7 controllers in modules](https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/)
   - [X] [Document How to use and override Ps 1.7 forms in modules](https://devdocs.prestashop.com/1.7/modules/concepts/forms/admin-forms/)
   - [ ] Every new feature introduced in 1.7.5 have his tests: migrated pages and Grid system.

**Comment by eternoendless** [comment]
👍

**Comment by eternoendless** [comment]
> more work on docs and tests AND a solution to be able to migrate Module controllers
Sounds good, but why "before" start a migration?

**Comment by mickaelandrieu** [comment]
> Sounds good, but why "before" start a migration?

It's always better to have a good and documented procedure before start a migration, if you disagree I encourage you to read again the ProductController :trollface:

**Comment by eternoendless** [comment]
Oh you meant "before start a _module_ migration". I thought you wanted to block all controller migrations, not just the modules. 👍

**Comment by mickaelandrieu** [comment]
Well, no :) I've done the roadmap with focus on having each one of them already "migrable" and independant of others! If we have 10 developers we could probably migrate all the remaining in 1 week :D

**Comment by kpodemski** [comment]
Hey @mickaelandrieu 

maybe you could mark somehow pages in progress? would be easier to choose something to do next

**Comment by kpodemski** [comment]
Nice :)

**Comment by Skullbock** [comment]
Hey @mickaelandrieu regarding "Document How to use and override Ps 1.7 commands in modules", is it already possible to register a custom command? I'm trying to add it as a service in a custom module, but it seems that it doesn't get added to the console command list.

Example:

```
services:
    _defaults:
        # make all services accessible directly from container
        public: true
        autoconfigure: true

    console.command.busato_import:
        class: CustomModule\Commands\ImportFromErp
        tags:
            -  { name: console.command, command: "erp:import" }
        public: true
```

Thanks!

**Comment by mickaelandrieu** [comment]
Hello @Skullbock, it should be available since 1.7.4 (even if it's not tested as it was'nt part of roadmap).

Let me check, also I can assure you it will be part of 1.7.5 :)

**Comment by Skullbock** [comment]
Seems that the PR in question is not available in 1.7.4.2
With that PR change and the .yml written as suggested it works!

Thanks!

**Comment by Skullbock** [comment]
Confirm that in 1.7.4.2 that PR change is not present so it doesn't work out of the box:

https://github.com/PrestaShop/PrestaShop/blob/1.7.4.2/src/PrestaShopBundle/PrestaShopBundle.php#L56

**Comment by Skullbock** [comment]
Sure, already done that, just wanted to confirm it so if other people need it it's written here ;)
Thanks!

**Comment by mickaelandrieu** [comment]
Update of 27/08/18 6 new pages added to the release with agreement of product team /c @eternoendless

**Comment by mickaelandrieu** [comment]
Closed as Symfony migration is now managed in the main [repository](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aopen+is%3Aissue+label%3Amigration)
