### ISSUE TITLE
Checklist with Grid component improvements

### ISSUE THREAD

**Issue by sarjon** [PrestaShop/prestafony-project#68]
This could be a checklist with Grid component improvements that _must_ be finished before **1.7.5** stable.

- [ ] Introduce Modifiers for Grid data. _(still needs to be discussed)_
- [ ] Finish up templating. _(PR https://github.com/PrestaShop/PrestaShop/pull/9281)_
- [ ] Introduce GridView object to make presented Grid immutable. _(still needs to be discussed)_
- [ ] Improve Data factories _(PR https://github.com/PrestaShop/PrestaShop/pull/9402)_
- [ ] Improve Filters component to make them accessible in multiple actions _(Issue https://github.com/PrestaShop/prestafony-project/issues/61, not a Grid component directly, but still important)_
- [ ] Add `Grid` prefix to `DefinitionInterface`, `Definition` and `FilterFormFactoryInterface` to follow current naming. _(there could be other classes as well)_
- [ ] Add more unit tests
- [ ] Finish up documentation
- [ ] Make Grid filter form (created by `FilterFormFactoryInterface`) more configurable, like form action, form method, data transformers & etc. _(still needs to be discussed)_
- [ ] `RowActionInterface` and `GridActionInterface` has `getIcon()` / `setIcon()` methods, we should either remove them or add same for `BulkActionInterface`.  _(still needs to be discussed)_
- [ ] Create module with custom Grid and existing Grid modification examples. _(Issue https://github.com/PrestaShop/prestafony-project/issues/63, PR https://github.com/sarjon/demo-grid-module)_
- [ ] Assets management in modules improvement. _(Issue https://github.com/PrestaShop/prestafony-project/issues/67)_

**Comment by mickaelandrieu** [comment]
Hello @eternoendless,

note that none of these items are required (except JavaScript stuff) to allow developers to customize their grids!

We're listing improvements here ^^

@sarjon I'll review on monday, I'm not available this weekend

**Comment by sarjon** [comment]
@mickaelandrieu dont forget this one. :)

**Comment by sarjon** [comment]
>> Introduce Modifiers for Grid data. (still needs to be discussed)

> Will be discussed in 1.7.6

@mickaelandrieu i think we should add this to 1.7.5, because:
1. legacy "grid" has this feature
2. while working on Categories grid i noticed I need it there as well (also Backup grid is waiting for it and i think Currencies grid will need it as well)

This feature is very small but also very important to have, wdyt?

**Comment by mickaelandrieu** [comment]
> also Backup grid

this page is merged so I can we can work without it for now? 1.7.6 will be released in january imo.

Also, we have already a hook to manipulate Grid data, even if it's a workaround it's good enough to buy us time to do a better system in 1.7.6

**Comment by sarjon** [comment]
For Backup it was easy to implement as workaround with private methods because backups are loaded from filesystem so i had to make new DataFactory. You can check Backup implementation [here](https://github.com/PrestaShop/PrestaShop/blob/develop/src/Core/Backup/Listing/BackupGridDataProvider.php#L102) 

However, it would be much harder for DoctrineDataFactory as it would require to create separate factory like CategoryDataFactory just to make small change. :/

**Comment by mickaelandrieu** [comment]
I know but it's only workarounds to buy us some time, we can't do everything at the same time and there are already a lot of required tasks to finish.

Believe me, 1.7.6 will be released after 1.7.5: this is not the end, this is the beginning :sunglasses:
